server.error.include-message=always

# No stack traces in REST response
server.error.include-stacktrace=never

# Database settings (values from environment variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

# Disable SQL logging in production
spring.jpa.show-sql=false

# Spring security settings
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# SMTP Settings
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

## Other SMTP properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

## TLS, port 587
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT configuration
jwt.issuer=msmtools
jwt.expiration-seconds=21600
jwt.refresh-expiration-seconds=30
jwt.pass-phrase=${JWT_PASSPHRASE}

frontend.url=${FRONTEND_URL}

# File upload size limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
