export enum MaterialTag {
  INDUSTRIALLY_COMPOSTABLE = 'INDUSTRIALLY COMPOSTABLE',
  RENEWABLE = 'RENEWABLE',
  REUSABLE = 'REUSABLE',
  LOCALLY_SOURCED = 'LOCALLY SOURCED',
  BY_PRODUCT = 'BY-PRODUCT',
  HOME_COMPOSTABLE = 'HOME COMPOSTABLE'
}
