export enum PostProcessingTag {
  MAKE_IT_YOURSELF = 'MAKE IT YOURSELF',
  MOLDED_CASTED = 'MOLDED/CASTED',
  PRINTED_3D = '3D PRINTED',
  LASER_CUT = 'LASER CUT',
  EXTRUDED = 'EXTRUDED',
  HOT_PRESSED = 'HOT PRESSED',
  COLD_PRESSED = 'COLD PRESSED',
  VACUUM_FORMED = 'VACUUM FORMED',
  FINISHING = 'FINISHING',
  NONE = 'NONE',
  OTHER = 'OTHER'
}
